<div class="container">
    <div class="row">
        <div class="col-6 ">
            <a class="login-text" href="<?= $block->getUrl('customer/account/login') ?>"> <i class="fas fa-user"></i>Login</a>
            
        </div>
        <div class="col-6">
        <a class="create-text" href="<?= $block->getUrl('customer/account/create') ?>"><i class="fas fa-address-card"></i> Register</a>
        </div>
    </div>

</div>